version: 1
evidenceRun: 28316015141
levels:
  ConfigMap: stable
  Secret: stable
  PersistentVolumeClaim: beta
  CronJob: stable
  Deployment: stable
  StatefulSet: stable
  Service: stable
  Namespace: stable
  DaemonSet: stable
  NetworkPolicy: experimental
  ServiceAccount: beta
  Role: beta
  ClusterRole: beta
  HorizontalPodAutoscaler: experimental
  Pod: beta
  Job: beta
